version: '3.8'
services:
  db:
    container_name: ozmapDB
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:${DB_PORT} --quiet
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: 'always'

  api:
    build: .
    container_name: ozmapApi
    working_dir: /api
    volumes:
      - ./src:/api/src
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    command: npm run dev
    depends_on:
      - db
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:${API_PORT}']
      timeout: 10s
      retries: 5

volumes:
  mongodb_data_container:
